"""The Get Started pages are generated from guides/*.toml by
scripts/build_guides.py and committed. These tests keep the committed HTML in
step with its source, pin the renderer's escaping, and stop a key or token
from ever being published through the guide content.
"""
from __future__ import annotations

import importlib.util
import re
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
GUIDES = ROOT / "guides"

_spec = importlib.util.spec_from_file_location("build_guides", ROOT / "scripts" / "build_guides.py")
bg = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(bg)

SLUGS = tomllib.loads((GUIDES / "site.toml").read_text(encoding="utf-8"))["nav"]["pages"]


def test_committed_pages_match_their_toml_source():
    for path, text in bg.build().items():
        assert path.exists(), f"{path.name} missing: run python scripts/build_guides.py"
        assert path.read_text(encoding="utf-8") == text, (
            f"{path.name} is stale: edit guides/pages/*.toml, then run python scripts/build_guides.py"
        )


def test_every_nav_page_has_a_source_file():
    for slug in SLUGS:
        assert (GUIDES / "pages" / f"{slug}.toml").exists()


def test_every_source_file_is_in_the_nav():
    on_disk = {p.stem for p in (GUIDES / "pages").glob("*.toml")}
    assert on_disk == set(SLUGS), "a page file exists that the nav does not list (or vice versa)"


# ---- secrets ----

SECRET_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9_-]{16,}"),          # OpenAI/OpenRouter/Anthropic style
    re.compile(r"sk-ant-[A-Za-z0-9_-]{8,}"),
    re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}"),     # GitHub tokens
    re.compile(r"AKIA[0-9A-Z]{16}"),               # AWS access keys
    re.compile(r"(?i)api[_-]?key\s*[:=]\s*['\"][^'\"]{12,}"),
]


@pytest.mark.parametrize(
    "path",
    sorted(GUIDES.rglob("*.toml")) + [SITE / f"{s}.html" for s in SLUGS],
    ids=lambda p: str(p.relative_to(ROOT)),
)
def test_no_secret_is_published(path):
    text = path.read_text(encoding="utf-8")
    for pattern in SECRET_PATTERNS:
        assert not pattern.search(text), f"{path.name} contains something shaped like a secret ({pattern.pattern})"


# ---- renderer ----


def test_inline_escapes_html_before_formatting():
    out = bg.inline("<script>alert(1)</script> **bold** `<b>`")
    assert "<script>" not in out
    assert "&lt;script&gt;" in out
    assert "<strong>bold</strong>" in out
    assert "<code>&lt;b&gt;</code>" in out


def test_inline_code_is_not_reformatted():
    assert bg.inline("`**not bold**`") == "<code>**not bold**</code>"


def test_inline_links_allow_only_safe_schemes():
    assert '<a href="https://x.org" rel="noopener">x</a>' in bg.inline("[x](https://x.org)")
    assert '<a href="/start.html">s</a>' in bg.inline("[s](/start.html)")
    assert "<a" not in bg.inline("[x](javascript:alert(1))")


def test_inline_italic_and_multiplication_star():
    assert bg.inline("*Try this*") == "<em>Try this</em>"
    assert "<em>" not in bg.inline("2 * 3 * 4")


def test_unknown_event_placeholder_is_an_error():
    with pytest.raises(bg.ContentError, match="event.nope"):
        bg.substitute("{event.nope}", {"name": "x"})


def test_unknown_block_type_names_the_file(tmp_path):
    (tmp_path / "pages").mkdir()
    (tmp_path / "site.toml").write_text('[event]\nname="E"\ndate="D"\n[nav]\npages=["p"]\n', encoding="utf-8")
    (tmp_path / "pages" / "p.toml").write_text(
        'title="T"\nnav_label="N"\nlede="L"\n[[sections]]\nid="s"\nheading="H"\n'
        '[[sections.blocks]]\ntype="carousel"\n',
        encoding="utf-8",
    )
    with pytest.raises(bg.ContentError, match=r"p\.toml.*carousel"):
        bg.build(tmp_path, tmp_path / "out")


def test_table_rows_must_match_headers():
    with pytest.raises(bg.ContentError, match="cells"):
        bg.table({"type": "table", "headers": ["a", "b"], "rows": [["only one"]]})


# ---- wiring ----


@pytest.mark.parametrize("page", ["index.html", "vote.html", "results.html"])
def test_core_pages_link_to_the_guides(page):
    assert 'href="/start.html"' in (SITE / page).read_text(encoding="utf-8")


@pytest.mark.parametrize("slug", SLUGS)
def test_guide_pages_are_marked_generated_and_have_one_h1(slug):
    html = (SITE / f"{slug}.html").read_text(encoding="utf-8")
    assert "GENERATED by scripts/build_guides.py" in html
    assert html.count("<h1") == 1


@pytest.mark.parametrize("page", ["index.html", "vote.html", "results.html"] + [f"{s}.html" for s in SLUGS])
def test_get_started_is_the_first_nav_item(page):
    html = (SITE / page).read_text(encoding="utf-8")
    nav = html[html.index('class="site-nav"'):]
    first_href = re.search(r'<a href="([^"]+)"', nav).group(1)
    assert first_href == "/start.html", f"{page}: first nav link is {first_href}"
